### ISSUE TITLE
vorpal.exec should return Promise

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#105]
@dthree Technically a breaking change but I think is important for consistency. Agree?

**Comment by dthree** [comment]
It.... does... doesn't it?

```js
vorpal.exec('foo').then(function(){

});
```

**Comment by scotthovestadt** [comment]
Something else must be wrong or I just missed something. Thanks.

**Comment by dthree** [comment]
No probs. :+1:
