### ISSUE TITLE
no-arg option support

### ISSUE THREAD

**Issue by mvayngrib** [dthree/vorpal#106]
some options, like --force, don't take an argument. Is there a way to specify such an option?

right now i have something like:

```js
vorpal
  .command('rm-provider <handle>', 'Remove a provider (irreversible)')
  .option('-f, --force', 'Don\'t second guess me')
  .action(function (args, cb) {
    //...
  })
```

and I'm running:

```bash
rm-provider -f someProviderName
```

and get the missing argument error (because `someProviderName` is interpreted as an argument to the option, and <handle> is left undefined):

```bash

  Missing required argument. Showing Help:

  Usage: rm-provider [options] <handle>


  Remove a provider (irreversible)

  Options:

    --help       output usage information
    -f, --force  Same thing without the second guessing
```

**Comment by dthree** [comment]
This is a big problem, it's been annoying me as well. Minimist, the arg parser, doesn't really take this into account so I really have to get under the hood to fix. Will do soon.

**Comment by mvayngrib** [comment]
@dthree awesome, thanks :)

**Comment by dthree** [comment]
Fixed.

https://github.com/dthree/vorpal/commit/8c091f948be99d55bb7120233285638c620c98b1

**Comment by jwthomp** [comment]
Awesome, thank you. 

It isn't clear to me how you push out new builds to npm, so just thought I'd ask when you expect this to be pushed? Thank you again!

**Comment by dthree** [comment]
Yeah. If I close a bug, it usually means I pushed to NPM. Sorry about not being clear. I'll note the push version in the future.

**Comment by jwthomp** [comment]
No worries at all. You certainly left enough breadcrumbs for me to figure it out on my own.

Cheers!
