### ISSUE TITLE
Optional and required arguments

### ISSUE THREAD

**Issue by AljoschaMeyer** [dthree/vorpal#11]
Hi, the issues just keep coming. I guess I'll have to take a look at the code soon and try to hack a pullrequest or two. I'm starting to feel bad for just posting these without trying to implement anything. Anyways, here we go:

```js
vorpal.command('test <required> [optional]')
```
`test foo` works as expected: `{ options: {}, required: 'foo' }`.  
However:
```js
vorpal.command('test [optional] <required>')
```
`test foo` results in `Missing required argument. Showing Help:`

It would be great if vorpal was smart enough to recognize that foo should be the value for `<required>`, not for `[optional]`.

**Comment by dthree** [comment]
Really, there's no problem at all. Vorpal is an infant so real-world feedback is very appreciated - issue or not!

That's a good idea, and should be pretty easy to implement.

**Comment by dthree** [comment]
This should be good now.
