### ISSUE TITLE
(Minor) Better help formatting

### ISSUE THREAD

**Issue by tarunc** [dthree/vorpal#111]
If the descriptions for help are too big for the terminal, the 2nd line can be indented. Just a thought for better help formatting.

Example:
![screen shot 2016-02-23 at 12 27 25 am](https://cloud.githubusercontent.com/assets/602762/13296833/46801a3c-dae4-11e5-8cb9-3f3f983d7d61.png)

Great module overall! Thanks!

**Comment by dthree** [comment]
I agree! Very good point and I've wanted to fix that. Feel free to send a PR, but otherwise I'll get to it fairly soon.

**Comment by dthree** [comment]
Fixed. Available in `v1.10.4`.
