### ISSUE TITLE
Installation fails on Windows - mindash is not found

### ISSUE THREAD

**Issue by ereOn** [dthree/vorpal#116]
I tried to install [`cash`](https://github.com/dthree/cash) which depends on `vorpal` but couldn't get it to install.

I'm no `npm` specialist (quite the opposite) but it seems that `https://registry.npmjs.org/mindash` returns a `404` error during `npm install`.

I tried to look for `mindash` but couldn't even find a Github repository for it.

Is this a known issue ?

**Comment by dthree** [comment]
My bad. Just did something very dumb. Give me a second.

**Comment by dthree** [comment]
Sorry about that. Latest version should be good now.

**Comment by ereOn** [comment]
I can confirm it works now. Thanks !

**Comment by dthree** [comment]
:+1:
