### ISSUE TITLE
Code `2` on clean exit

### ISSUE THREAD

**Issue by omnidan** [dthree/vorpal#118]
When exiting via `exit` or Ctrl+C, vorpal seems to quit with an exit code of `2`.

This makes `npm` show errors when running the script within `npm start`.

**Comment by dthree** [comment]
Do you know what should be expected from `SIGINT`? This should be a simple fix.

**Comment by omnidan** [comment]
@dthree `node` itself exits with return code `0` on Ctrl+C

```
bash-4.3$ node
>
(To exit, press ^C again or type .exit)
>
bash-4.3$ echo $?
0
```

**Comment by dthree** [comment]
K thanks.

**Comment by dthree** [comment]
Fixed. Live in `v1.10.3`.

**Comment by omnidan** [comment]
@dthree Awesome! :+1:
