### ISSUE TITLE
Compiler doesn't reach end stage

### ISSUE THREAD

**Issue by Shakyamuni177te** [dthree/vorpal#119]
The compiler won't reach the end stage after I finished reconfiguring a null object. Is this an issue with the interfacing infrastructure and not the app itself?

**Comment by dthree** [comment]
Could you give me an example of what your code is and what the error is?

**Comment by dthree** [comment]
Throw me some code and I'll re-open this. Not enough data to do anything with.

**Comment by Shakyamuni177te** [comment]
​What about the meta-data? Have you filed a formal request with the
relevent department?

**Comment by Shakyamuni177te** [comment]
Might be something to do with:

parseArgs: function (str, opts) {
    const reg = /"(.*?)"|'(.*?)'|`(.*?)`|([^\s"]+)/gi;
    let arr = [];
    let match;
    do {
      match = reg.exec(str);
      if (match !== null) {
        arr.push(match[1] || match[2] || match[3] || match[4]);
      }
    } while (match !== null);

    arr = minimist(arr, opts);
    arr._ = arr._ || [];
    return arr;
  },
