### ISSUE TITLE
Fail fast when adding duplicate commands

### ISSUE THREAD

**Issue by AljoschaMeyer** [dthree/vorpal#12]
Guess I'll just drown you in feedback then.

Duplicate commands sit in the background until invoked, silently overriding each other. I also got a crash because of that (I think), which I unfortunately did not manage to replicate.

Especially with functions like vorpal-use, the user should at least be notified when a duplicate command is added. I didn't look how you implemented aliases, but the same should be true there.

And at the very least, you'll save some devs debugging time.

**Comment by dthree** [comment]
> Guess I'll just drown you in feedback then.

Haha!

**Comment by dthree** [comment]
Vorpal's blowing up on HN... guess I'd better fix these fast :)

**Comment by dthree** [comment]
@melonmanchan was rad enough to fix this.
