### ISSUE TITLE
Show Inquirer default value

### ISSUE THREAD

**Issue by devinus** [dthree/vorpal#125]
Inquirer shows default values, but Inquirer used from Vorpal does not.

Inquirer:
<img width="267" alt="screen shot 2016-03-02 at 11 24 46 am" src="https://cloud.githubusercontent.com/assets/4836/13468683/74431020-e069-11e5-8549-ef2464696ae0.png">

Vorpal:
<img width="260" alt="screen shot 2016-03-02 at 11 25 39 am" src="https://cloud.githubusercontent.com/assets/4836/13468700/8717f896-e069-11e5-964a-fcfe568214c9.png">

**Comment by dthree** [comment]
Thanks. To assist in debug, could you give me the code you used to reproduce this? Thanks.

**Comment by MatthieuLemoine** [comment]
I have the same issue. It can be reproduce with

```javascript
vorpal
  .command('setup')
  .description('Setup your cli / Update your informations')
  .action(function action(args, cb) {
    this
      .prompt([
        {
          type    : 'input',
          name    : 'name',
          message : 'Enter your name : ',
          default : 'defaultName',
        },
      ])
      .then(answers => {
        cb(`Welcome ${answers.name}!`);
      })
      .catch(err => cb(err));
  });
```
