### ISSUE TITLE
Command history "up" after executing command should always show last command

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#126]
I think the behavior that prevents sequential command of the same command from showing twice is preventing me from seeing the last command in some cases. This is annoying because I will muscle-memory execute the wrong command sometimes.

**Comment by dthree** [comment]
Ooh got it.K,

**Comment by scotthovestadt** [comment]
Fixed.

**Comment by scotthovestadt** [comment]
I added a test for the behavior, too.
