### ISSUE TITLE
Vorpal fails to install on Windows 10 using most recent npm installation

### ISSUE THREAD

**Issue by Shakyamuni177te** [dthree/vorpal#128]
![image](https://cloud.githubusercontent.com/assets/11525524/13549094/b9a5e8ce-e2f6-11e5-99c9-cd667439ea4d.png)

**Comment by Shakyamuni177te** [comment]
npm-debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\fujitsu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'vorpal' ]
2 info using npm@3.8.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData vorpal
8 silly fetchDirectoryPackageData vorpal
9 silly install normalizeTree
10 silly loadCurrentTree Finishing
11 silly loadIdealTree Starting
12 silly install loadIdealTree
13 silly cloneCurrentTree Starting
14 silly install cloneCurrentTreeToIdealTree
15 silly cloneCurrentTree Finishing
16 silly loadShrinkwrap Starting
17 silly install loadShrinkwrap
18 silly loadShrinkwrap Finishing
19 silly loadAllDepsIntoIdealTree Starting
20 silly install loadAllDepsIntoIdealTree
21 silly resolveWithNewModule vorpal@1.10.8 checking installable status
22 silly cache add args [ 'vorpal', null ]
23 verbose cache add spec vorpal
24 silly cache add parsed spec Result {
24 silly cache add   raw: 'vorpal',
24 silly cache add   scope: null,
24 silly cache add   name: null,
24 silly cache add   rawSpec: 'vorpal',
24 silly cache add   spec: 'C:\\Command\\vorpal',
24 silly cache add   type: 'directory' }
25 verbose addLocalDirectory C:\Users\fujitsu\AppData\Roaming\npm-cache\vorpal\1.10.8\package.tgz not in flight; packing
26 verbose correctMkdir C:\Users\fujitsu\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 info lifecycle vorpal@1.10.8~prepublish: vorpal@1.10.8
28 verbose lifecycle vorpal@1.10.8~prepublish: unsafe-perm in lifecycle true
29 verbose lifecycle vorpal@1.10.8~prepublish: PATH: C:\Users\fujitsu\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Command\vorpal\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files\iis express\PHP\v7.0;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Graphviz 2.28\bin; c:\php; c:\Apache24; c:\Apache24\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby2.1.0\bin;C:\RailsInstaller\Ruby2.0.0\bin;C:\ProgramData\fujitsu\atom\bin;C:\Users\fujitsu\AppData\Roaming\npm;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby2.1.0\bin;C:\RailsInstaller\Ruby2.0.0\bin;C:\ProgramData\fujitsu\atom\bin;C:\Users\fujitsu\AppData\Roaming\npm
30 verbose lifecycle vorpal@1.10.8~prepublish: CWD: C:\Command\vorpal
31 silly lifecycle vorpal@1.10.8~prepublish: Args: [ '/d /s /c', 'gulp build;' ]
32 silly lifecycle vorpal@1.10.8~prepublish: Returned: code: 1  signal: null
33 info lifecycle vorpal@1.10.8~prepublish: Failed to exec prepublish script
34 error addLocal Could not install C:\Command\vorpal
35 silly rollbackFailedOptional Starting
36 silly rollbackFailedOptional Finishing
37 silly runTopLevelLifecycles Starting
38 silly runTopLevelLifecycles Finishing
39 silly install printInstalled
40 verbose stack Error: vorpal@1.10.8 prepublish: `gulp build;`
40 verbose stack Exit status 1
40 verbose stack     at EventEmitter.<anonymous> (C:\Users\fujitsu\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
40 verbose stack     at emitTwo (events.js:100:13)
40 verbose stack     at EventEmitter.emit (events.js:185:7)
40 verbose stack     at ChildProcess.<anonymous> (C:\Users\fujitsu\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
40 verbose stack     at emitTwo (events.js:100:13)
40 verbose stack     at ChildProcess.emit (events.js:185:7)
40 verbose stack     at maybeClose (internal/child_process.js:827:16)
40 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
41 verbose pkgid vorpal@1.10.8
42 verbose cwd C:\Command
43 error Windows_NT 10.0.10240
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fujitsu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "vorpal"
45 error node v5.6.0
46 error npm  v3.8.0
47 error code ELIFECYCLE
48 error vorpal@1.10.8 prepublish: `gulp build;`
48 error Exit status 1
49 error Failed at the vorpal@1.10.8 prepublish script 'gulp build;'.
49 error Make sure you have the latest version of node.js and npm installed.
49 error If you do, this is most likely a problem with the vorpal package,
49 error not with npm itself.
49 error Tell the author that this fails on your system:
49 error     gulp build;
49 error You can get information on how to open an issue for this project with:
49 error     npm bugs vorpal
49 error Or if that isn't available, you can get their info via:
49 error     npm owner ls vorpal
49 error There is likely additional logging output above.
50 verbose exit [ 1, true ]

**Comment by Shakyamuni177te** [comment]
Have checked gulp is installed:

![image](https://cloud.githubusercontent.com/assets/11525524/13549181/58dfbf54-e2f8-11e5-9a5b-d16629956c1c.png)

and made sure the package.json in my command line library available:

![image](https://cloud.githubusercontent.com/assets/11525524/13549199/8ae44934-e2f8-11e5-9c7f-88cdf2ed9634.png)

Same error still.

**Comment by scotthovestadt** [comment]
@Shakyamuni177te It looks like this is an issue with the prepublish hook being called after install, which is very unintuitive. For now, if you add vorpal as a dependency to your package.json and just run "npm install", it'll install correctly.

I'll look into a workaround.

See here for details and other people complaining about this:
https://github.com/npm/npm/issues/3059

**Comment by scotthovestadt** [comment]
OK, should be fixed now.

@dthree Can you publish?
