### ISSUE TITLE
Command option with equal sign isn't parsed correctly

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#130]
Failing test:
````js
it('should parse equal sign command option', function (done) {
  exec('say "hello=world"', done, function () {
    stdout().should.equal('hello=world');
  });
});
````

**Comment by scotthovestadt** [comment]
Oh, it looks intentional. It breaks something I wrote but I'll just change it to use a colon or something.

**Comment by dthree** [comment]
Yah just did something recently on this.

**Comment by scotthovestadt** [comment]
@dthree This issue is causing major headaches for me. It's impossible to pass a SQL string via command-line arguments. I need an option to turn it off. I'm working on it now.

**Comment by dthree** [comment]
:+1: all good, the flag is fine with me.

Thanks.
