### ISSUE TITLE
How to add a spinner with vorpal?

### ISSUE THREAD

**Issue by steelbrain** [dthree/vorpal#132]
Currently we have a `.log` that fits the basic needs, but what if I wanted to create a spinner. How would I make vorpal work with that? Any help would be appreciated

**Comment by dthree** [comment]
Check out the `vorpal.ui.redraw` methods:

https://github.com/dthree/vorpal/wiki/api-|-vorpal.ui

**Comment by steelbrain** [comment]
> If this helped, would you mind posting this question on StackOverflow so others can benefit from the answer? Thanks!

IIRC github issues show up on google searches so IMHO this is already benefiting for those who seek :)

**Comment by dthree** [comment]
Not as well and high as SO, but not a big deal either way. :)
