### ISSUE TITLE
Question: Where is the interactive menu like Inquirer.js

### ISSUE THREAD

**Issue by kevincaradant** [dthree/vorpal#135]
Hi

Sorry for this question , but i searched in the documentation the interactive menu. But I didn't find it. So I ask you if you know where is it .

I'm searching something like that : 

![image](https://cloud.githubusercontent.com/assets/6093175/13842387/2bbbdc80-ec2e-11e5-97ce-4349166e3ae9.png)

Thank you by advance :)

**Comment by dthree** [comment]
Hey, no problem.

Inquirer.js is directly exposed through `this.prompt` while mid an action. This means you can just refer to Inquirer's documentation at that point.

https://github.com/dthree/vorpal/wiki/api-|-CommandInstance

See above for more details.

**Comment by kevincaradant** [comment]
Ah yes, you're right. It's more clear for me. Thank you very much :)
