### ISSUE TITLE
`required` `option` are acting like `optional`

### ISSUE THREAD

**Issue by petvas** [dthree/vorpal#136]
```js
vorpal
    .command('stringify')
    .option('-a, --amount <amt>', 'A number to stringify.')
    .types({
        string: ['a', 'amount']
    })
    .action(function (args, cb) {
        this.log(args.options);
        cb();
    });
```

example Outputs:
`stringify -a asd` : `{ amount: 'asd' }`

`stringify` : `{}`

problem:
` --amount <amt>` means it is required `vorpal` shousd not execute a `command` if required options not used.

src: https://github.com/dthree/vorpal/wiki/api-%7C-vorpal.command#commandoptionstring-description-autocomplete

**Comment by scotthovestadt** [comment]
Per @dthree this is currently expected behavior. When you provide the option, the param is required, but the actual option itself isn't required. You can use a validate hook to ensure the option is provided.
