### ISSUE TITLE
Welcome message?

### ISSUE THREAD

**Issue by AriaFallah** [dthree/vorpal#141]
Is there a way to make a welcome message for the CLI when it's first invoked?

Something like:

```bash
Welcome to CLI, try running "help" to see what you can do!
cli $ 
```

**Comment by dthree** [comment]
I would probably just do this:

```
vorpal.show();
vorpal.log('Welcome to CLI, try running "help" to see what you can do!');
```

**Comment by AriaFallah** [comment]
@dthree just realized I can also do a simple `console.log()`...

Thank you!

**Comment by dthree** [comment]
Sure! For the record, don't do `console.log` as this will mess with the prompt. `vorpal.log` properly redraws the prompt after logging.
