### ISSUE TITLE
nodemon messes up vorpal command history 

### ISSUE THREAD

**Issue by dkebler** [dthree/vorpal#149]
when vorpal is launched from within nodemon, the command history is non-functional.   Instead of previous commands appearing with the up cursor you get ` ^[[A`

**Comment by Offirmo** [comment]
Same problem. Answered as the 1st entry in nodemon FAQ https://github.com/remy/nodemon/blob/master/faq.md#nodemon-doesnt-work-with-my-repl

If using the "restartable" option, nodemon takes over stdin to catch the manual restart command. Using ` "restartable": false` solves the problem.

**Comment by dthree** [comment]
@dkebler can you try that and let me know? 

--

I threw this in the Wiki:

https://github.com/dthree/vorpal/wiki/Docs-%7C-Integration

**Comment by dkebler** [comment]
just now saw this.  Thanks! working like a charm!
