### ISSUE TITLE
Command names with capital letters

### ISSUE THREAD

**Issue by AljoschaMeyer** [dthree/vorpal#15]
Adding a command with capital letters does not work.

Running it (either correctly written or in lowercase) yields `Invalid Command. Showing Help:`.
The help does include this:
```
fooBar                undefined
```  

If forcing all-lowercase command names is intentional, a notification when an invalid command is added would be nice. If its unintentional: well, more stuff to fix =)

```js
vorpal.command('fooBar')
  .action(function(args, cb) {
    this.log 'fooBar';
    cb();
});
```
\* Not my actual code, please ignore js errors produced by my blissful, coffeescript-induced ignorance.

**Comment by dthree** [comment]
It was intentional, but not the most intelligent foresight. I should change this.

**Comment by dthree** [comment]
This is fixed now.
