### ISSUE TITLE
How to separate commands into files

### ISSUE THREAD

**Issue by minhchu** [dthree/vorpal#157]
I have many commands and each of them is long.
For example, I have:

- create
- read
- update
- delete
....

I wants to put them in separate files:

- ./commands/create.js
- ./commands/read.js
- ./commands/update.js
- ./commands/delete

and I want to require them in `app.js`:
```
require('./commands/create.js');
...
```
so I can:
`node app.js create HelloWorld`

How can I achieve this. Thank you.

**Comment by dthree** [comment]
I would do something like this:

```

**Comment by minhchu** [comment]
Thank you. It works. I dont know that extension can be used this way :+1: 
Btw, here is the question, you can answer it :grin: http://stackoverflow.com/questions/38261365/how-to-separate-commands-into-files-vorpal-js
