### ISSUE TITLE
vorpal.parse() method has breaking changes to behaviour in 1.11.4

### ISSUE THREAD

**Issue by allmarkedup** [dthree/vorpal#172]
v1.11.4 seems to have had a breaking change in the behaviour of the `vorpal.parse()`. Prior to this version this method parsed the command string but did not attach a UI, which was great because (as I was using it) commands could be triggered directly if required (for instance when running tasks on a server), instead of dropping into 'interactive mode'.

Since 1.11.4 this is no longer the case. Is this change intentional (if so I feel like it requires a major version bump as this is certainly a breaking change) or an unintended consequence of another change?

**Comment by dthree** [comment]
We're about to fix this. Please see this existing issue:

https://github.com/dthree/vorpal/pull/169

**Comment by allmarkedup** [comment]
Ah perfect - I must have somehow missed the other issue in my skim through the list. Good to know that you are on it.

Vorpal is awesome, btw. Great work.
