### ISSUE TITLE
Maintainer Request

### ISSUE THREAD

**Issue by LongLiveCHIEF** [dthree/vorpal#187]
I'd like to become a maintainer/owner of this project.  Much :heart: for it, and I have used it so many times over the last year, that I don't want to see it fade away.  I can also host or maintain the website/domain if needed.

**Comment by SteveEmmerich** [comment]
Hi @LongLiveCHIEF I would like to join you in maintaining this project. Could I be of help or do you have it under control?

**Comment by LongLiveCHIEF** [comment]
I haven't received a response back from @dthree yet, but I'll let you know when I do.

**Comment by LongLiveCHIEF** [comment]
Withdrawing per comments in #189

**Comment by dthree** [comment]
Hi, so sorry. Just seeing this. Are  you two still interested in this?

**Comment by LongLiveCHIEF** [comment]
Yep, absolutely.  I also close PR #189 which I can reopen after adding @SteveEmmerich's info to the maintainers block if you'd like.

**Comment by dthree** [comment]
Okay, great! 

Most wanted right now is closing simple issues and PRs, without changing major functionality. I'll try to put in some time soon to catch up and go over more with you.

For any breaking changes, please get with me before committing, until you've gotten some more familiarity with the project.

Sound good?

**Comment by minhchu** [comment]
This package is great. Hope you can continue to maintain it :+1:

**Comment by dthree** [comment]
Thanks @minhchu . I'm hoping to find some time in the future to do a number on it and clean up all issues.
