### ISSUE TITLE
Minimize lodash dependencies

### ISSUE THREAD

**Issue by Downchuck** [dthree/vorpal#2]
It looks like only a few methods from lodash are in use; the library is available in modular form:
https://www.npmjs.com/browse/keyword/lodash-modularized

**Comment by dthree** [comment]
Yeah - was thinking about doing that. Will do. 

BTW, this is a pretty simple fix. Do you think you'd have a chance to do a PR on this? That'd be very helpful.

**Comment by Downchuck** [comment]
I think I can get that handled.

**Comment by dthree** [comment]
Grt!

**Comment by dthree** [comment]
Okay this is dumb. I didn't realize I used so many lodash functions: as each sub-module comes with the overhead of a readme, license, etc. the total size ended up greater than importing lodash by itself.

:(
