### ISSUE TITLE
Refresh delimiter on no command (just hit Enter)

### ISSUE THREAD

**Issue by jstrika** [dthree/vorpal#204]
Hi, 

It might be one of the questions already asked, but could not find the answer.

How to capture dialog without any arguments? I tried with parse and catch, but its not triggered on event without any arguments.

Why I need it? I'm using delimiter to represent the status of my app, which can also be changed using web interface. So I would like to refresh prompt on RETURN

**Comment by MatthieuLemoine** [comment]
You can update the delimiter using 
```javascript
vorpal.ui.delimiter('delimiter');
```
If you want to update it on Enter press you can add a ``keypress`` listener to ``process.stdin``: 
```javascript
process.stdin.on('keypress', (_, key) => {
  if (key && key.name === 'return') {
    vorpal.ui.delimiter(newValue);
  }
});
```

**Comment by jstrika** [comment]
Great, works as advertised.

Thanks!
