### ISSUE TITLE
compatibility issues when using JXCore. 

### ISSUE THREAD

**Issue by ozzie1998** [dthree/vorpal#205]
trying to start the app with JXCore results in: 

    `const vorpal = require("vorpal")();
       ^^^^^
    SyntaxError: Use of const in strict mode.`

**Comment by MatthieuLemoine** [comment]
@ozzie1998 Use ``var vorpal = require('vorpal')();`` instead

**Comment by ozzie1998** [comment]
Any idea what could cause the slow startup? it takes a good few seconds to start.

**Comment by MatthieuLemoine** [comment]
It depends on your app, your computer, your CPU load...

My app takes between 1s and 4s to start. It includes parsing and execution time.

**Comment by ozzie1998** [comment]
Okay, thank you. I guess a 1.7ghz is not the best then.
