### ISSUE TITLE
Feature request: Ruby gem

### ISSUE THREAD

**Issue by PeterDavidCarter** [dthree/vorpal#215]
Given the major improvements to Ruby on Rails in the last two versions, to the point it has eclipsed even Node based web solutions even it its areas of historical weakness (e.g. post-deployment speed) I plan to work primarily in Ruby from now on, and foresee many others doing the same. This will likely also affect my preferences in CLI apps, and when I begin writing these it will be in Ruby as first preference over Node, Python, Bash script etc, due in large part to the elegance and coder-friendliness of the language, as well as the fact I will be using Rails elsewhere, so advanced knowledge of the language will necessitate some degree of specialization.

As such, and accepting that even Rails utilizes JavaScript when unavoidable, as there any chance of a version of this library that's a Ruby gem?

**Comment by MatthieuLemoine** [comment]
You should check : https://github.com/markets/awesome-ruby#cli-builder

**Comment by milesj** [comment]
I don't think this will happen. Closing this.
