### ISSUE TITLE
Variadic and optional argument case

### ISSUE THREAD

**Issue by radixzz** [dthree/vorpal#216]
Hi everyone!

Not sure if the following behavior is by design but:

``` javascript
vorpal
    .command('cmd <a...> [b]', 'Test case"')
    .action(function(args, callback) {
        console.log( args );
        callback();
    });
```
with the input `cmd 1 2` will parse the args inside action without the 1:

```
{ options: {}, a: [ 2 ], b: 2 }
```

Is this a bug? or am I misusing the variadic and optional arguments?.
Thank you!

**Comment by omidfi** [comment]
I guess variadic arguments can be used only as the last argument

**Comment by milesj** [comment]
@radixzz 

Omidfi is correct, variadics must be last: https://github.com/dthree/vorpal/blob/master/lib/vorpal.js#L311

They work in a similar vein to rest arguments: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters
