### ISSUE TITLE
Feature request: Auto-complete when typing piped commands

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#22]
````reverse hello | rev````

Hit tab. No autocomplete.

Looks like it's possible to implement even with the API but would be nice to detect the pipe character and have it built in!

**Comment by dthree** [comment]
Good point - this would be good to have.

Not sure yet whether this will be tricky or simple to implement. I'll check it out.

**Comment by scotthovestadt** [comment]
I'll add this feature.

**Comment by dthree** [comment]
That'd be cool. Check out the ._exec command in `index.js`

**Comment by scotthovestadt** [comment]
I've made a pull request. Let me know if there's anything more I need to do to have it merged in!

**Comment by dthree** [comment]
Thanks! Looks good on cursory glance - I want to make sure it doesn't break more detailed use of autocompletion, such as on `wat`, which does some crazy things.

Could you rebase your branch with the linting I put in, and I'll try to get this merged as soon as possible!

**Comment by scotthovestadt** [comment]
Done.

**Comment by dthree** [comment]
Boom.
