### ISSUE TITLE
BUG: Terminal breaks when input is too wide

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#23]
When I input past the width of the terminal, my input (in this case random numbers) goes onto the next lines.

````
deliminator$: 12313131313123131313131313213213111111111231323344
1123132334
112313233
11231323
1123132
112313
11231
1123
112
11
1
````

**Comment by Shakyamuni177te** [comment]
What OS are you working on? And what GUI?

**Comment by dthree** [comment]
I can't reproduce this - what's your OS and terminal?

**Comment by Shakyamuni177te** [comment]
Also, couple you post the code? So I can maybe help dthree look into it too? :)

**Comment by scotthovestadt** [comment]
Mac OSX Yosemite, 10.10.4. Standard terminal. Checking to see if can reproduce in example projects. See attachment for video:

![blankthoughtfulhyracotherium](https://cloud.githubusercontent.com/assets/1831484/10547154/7ee6c768-73e7-11e5-82ee-361d102f2eca.gif)

**Comment by dthree** [comment]
Huh. Could you download `inquirer.js` standalone and try an Inquirer prompt and see if its the same problem? Vorpal's prompt is based on Inquirer, so it might be his bug.

**Comment by dthree** [comment]
https://github.com/SBoudrias/Inquirer.js/

**Comment by scotthovestadt** [comment]
Confirmed it reproduces in "calculator" example. Trying standalone Inquirer.

**Comment by scotthovestadt** [comment]
Yes, it's Inquirer. What environments are you guys on where it DOESN'T happen for you? I'd like to let my users know.

**Comment by dthree** [comment]
You already have people using Vorpal? That was fast.
I'm unfortunately developing on Windows. And tried it on Putty as well.

**Comment by Shakyamuni177te** [comment]
Linux Mint, Cinnamon 64 bit. Confirmed works fine for me.

**Comment by scotthovestadt** [comment]
Thanks guys, I'll look into the Inquirer side.

PS: Love Vorpal. Especially the built-in pipes.

**Comment by dthree** [comment]
Filed it. And thanks man :)

**Comment by scotthovestadt** [comment]
For anyone finding this on Google, here is a workaround:

Using ````require('cli-clear')()```` will reset terminal input and everything works correctly from that state. Do it once at the beginning of your app.

**Comment by abramdemski** [comment]
I am still having this problem on Mac, in this project: https://github.com/dranorter/metaprompt_command
