### ISSUE TITLE
Links at the bottom of the wiki are just empty hashes

### ISSUE THREAD

**Issue by Shakyamuni177te** [dthree/vorpal#24]
Do you want me to fix those? I'd need to know what you wanted written in those boxes, or just the gist of the info...

**Comment by dthree** [comment]
Whoops - forgot about that.

I added what I want to put there, just haven't done the links. If you could fill this in with the link (to eac Wiki page it mentions), that would be amazing!

```
<p align='center'>
  <a href='#'>vorpal</a>&nbsp;&nbsp;•&nbsp;&nbsp;
  <a href='#'>command</a>&nbsp;&nbsp;•&nbsp;&nbsp;
  <a href='#'>mode</a>&nbsp;&nbsp;•&nbsp;&nbsp;
  <a href='#'>catch</a>&nbsp;&nbsp;•&nbsp;&nbsp;
  <a href='#'>ui</a>&nbsp;&nbsp;•&nbsp;&nbsp;
  <a href='#'>CommandInstance</a>&nbsp;&nbsp;•&nbsp;&nbsp;
  <a href='#'>Events</a>&nbsp;&nbsp;•&nbsp;&nbsp;
</p>
```

**Comment by Shakyamuni177te** [comment]
Absolutely. I'll do that now :).

**Comment by dthree** [comment]
Thanks! :+1:

**Comment by dthree** [comment]
Oddly, the footer doesn't read markdown links. Random. So, yeah, we have to use `<a>` tags.

**Comment by Shakyamuni177te** [comment]
Done and tested working.

Thank you for the opportunity to work on this project. :)

**Comment by Shakyamuni177te** [comment]
Ok, seems not to now. Just a second...

**Comment by Shakyamuni177te** [comment]
Working again. Weird...

**Comment by dthree** [comment]
Nice! Thanks!! :+1:
