### ISSUE TITLE
Question about dist directory packaging on NPM

### ISSUE THREAD

**Issue by ORESoftware** [dthree/vorpal#252]
I think it's cool that you package this project in the dist directory when it's packaged on NPM - just wondering how you do that, I am thinking about doing that with one of my projects but not sure how or the best way to do it. Any explanation would be cool to hear, thanks.

**Comment by milesj** [comment]
Pre-2.0 versions use Gulp to build to a dist/ folder: https://github.com/dthree/vorpal/blob/2.0/gulpfile.babel.js#L13

2.0+ will use Babel directly and build to a lib/ folder.

**Comment by ORESoftware** [comment]
cool thanks, any word on that bug issue I opened..I'd like to start using this lib - maybe I can use an older version for now?
