### ISSUE TITLE
Error first callbacks not available with autocomplete?

### ISSUE THREAD

**Issue by ORESoftware** [dthree/vorpal#254]
Maybe the example is wrong (a doc bug), but in the tab completion section I see:

```js
vorpal.command('feed [animal]')
  .autocomplete({
    data: function (input, callback) {
      getAnimals(function (array) {
        callback(array);            // << not an error-first callback?
      });
    }
  })
  .action(feedThem);
```

this seems incorrect - if we returned `Promise.reject('some error')`, then vorpal should handle that somehow.

Likewise, if we have an error, we should be able to pass the error as the first argument to the callback. Is this a doc bug, or something more concerning?

**Comment by oboecat** [comment]
Is there any update on this?

**Comment by ORESoftware** [comment]
yeah I think vorpal version 1.x just doesn't have error first callbacks in some places, hopefully with version 2 they fix that pattern.
