### ISSUE TITLE
eslint config file doesn't appear to be committed

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#26]
Running ````gulp lint```` yields many errors.

**Comment by scotthovestadt** [comment]
Might also be a smart idea to add eslint ````gulp test```` to ````npm test```` so Travis CI will pick up on it for pull requests. After the config file is added.

**Comment by dthree** [comment]
Ouch. I had it on, but was doing a lot of dev and so took it off. Putting it back on. :)

It's [xo](github.com/sindresorhus/xo)-linted, and properly configured for that.

**Comment by dthree** [comment]
All good - enforced as well.
