### ISSUE TITLE
Alternative to non maintained Minimist package

### ISSUE THREAD

**Issue by diego-G** [dthree/vorpal#260]
Minimist is not maintained by their authors. They have 33 open issues not answered, 21 open PR and last commit was 2 years ago.

This situation is raising issues to Vorpal.

Community would appreciate if you find an alternative to replace it. My recommendation it is https://github.com/tj/commander.js which has an active community of developers.

**Comment by milesj** [comment]
Commander and Vorpal are equivalent libraries. They could even be considered competitors.

That being said, we have plans to rework argument parsing in v2.

**Comment by diego-G** [comment]
Thanks for your fast reply. Hence I've changed the title to the real purpose of my issue. Hope you can find a way to get rid of that package.

**Comment by ORESoftware** [comment]
dashdash is an excellent arg parser, although I assume you have already chosen an argument parser for Vorpal version 2.

https://github.com/trentm/node-dashdash

**Comment by diego-G** [comment]
Unanswered.
