### ISSUE TITLE
Ouput of data with prettyJson package removes the cursor

### ISSUE THREAD

**Issue by StarpTech** [dthree/vorpal#273]
Hi, I implemented a command which ouutput the result of an action as coloured YAML-style with the https://github.com/rafeca/prettyjson package. It look like that printing the data turns the console in a different mode because only after keypress event the vorpal line `local@starptech~$` appears

```js
vorpal.ui.redraw(Prettyjson.render(err || resp))
```

Any idea why the cursor is removed? Only restarting the cli will bring back the default behaviour. Thanks.

**Comment by dthree** [comment]
Have you checked to see if this only happens with prettyJSON? It might just be your use of `redraw`.

Check out the docs:

https://github.com/dthree/vorpal/wiki/API-%7C-vorpal.ui

You might have to do `ui.redraw.done` afterwards.

**Comment by StarpTech** [comment]
HI @dthree the fix works thanks!
