### ISSUE TITLE
Context for repl mode

### ISSUE THREAD

**Issue by thetutlage** [dthree/vorpal#29]
How about having context for repl mode , the way we can attach `context` with account nodejs repl

**Comment by thetutlage** [comment]
I got it , nice work man

**Comment by dthree** [comment]
I guess you figured out how to do it? :)

**Comment by thetutlage** [comment]
Yes completely :+1:

**Comment by dthree** [comment]
Great! And thanks :)

**Comment by mbanduk** [comment]
Could you guys explain how to do so?

Thanks

**Comment by mrpatiwi** [comment]
How to add context? Would be helpful for future users
