### ISSUE TITLE
Bump inquirer version

### ISSUE THREAD

**Issue by Downchuck** [dthree/vorpal#3]
inquirer@0.9.0 is about half the size, as they switched to "rx-lite" from the much larger rxjs package.
They have also "fixed" their lodash dependency, though that one is including the full librayr (now the bulk of the distribution size).

**Comment by dthree** [comment]
Nice. I know the semver says as much, but are you aware of any breaking changes with that switch?

**Comment by dthree** [comment]
@Downchuck snap I upgrade, and it totally broke Vorpal haha.

Vorpal uses a ton of the internals of inquirer as it gets down and dirty on UI manipulation, so I'm digging in to find what changed. 1/10th the size is definitely an enticing goal to get working.

**Comment by dthree** [comment]
For the record, this is fixed :)

**Comment by Downchuck** [comment]
fixed in 1.0.4; https://github.com/dthree/vorpal/commit/3e676e9fa0038893d777ca9a720a1f85bbc3de4e

**Comment by dthree** [comment]
Fully fixed in `1.0.7`. Pressing the `tab` key still had some unexpected ramifications.
