### ISSUE TITLE
Pressing tab to autocomplete in the middle of a string actually prints tab

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#32]
If I start typing my command:
````command-one param | command-two param````

Then I go back and try to edit command-one and change it to command-three, put my cursor here:
````com_ | command-two param````

Then I hit tab, it actually prints tab. No autocomplete. I think the code doesn't even think about the cursor position. Is it possible to react to the cursor pos?

**Comment by dthree** [comment]
I think I intentionally check if the cursor is at the end, but maybe that's a bad idea. Should be a quick fix.

**Comment by dthree** [comment]
Okay this was actually really tricky, but should be good now.
