### ISSUE TITLE
BUG: vorpal.exec never fires callback with piped commands when using promises

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#33]
Looks like it affects promises only. The first command resolves, subsequent piped commands promise doesn't seem to be seen as resolved.

**Comment by scotthovestadt** [comment]
This issue is this block in command-instance.js

````js
var res = fn.call(self.downstream, self.downstream.args, function () {
  self.session.completeCommand();
});
````

It's assuming that the command will return a callback instead of a promise. In other places, both types are accounted for. The fix is pretty simple:

````js
var onComplete = function () {
  self.session.completeCommand();
};
var res = fn.call(self.downstream, self.downstream.args, onComplete);
if (res && res.then) {
  res.then(onComplete, onComplete);
}
````

**Comment by dthree** [comment]
Good find. Would you mind throwing in a PR for that?

**Comment by scotthovestadt** [comment]
Done. If you wouldn't mind doing a release after you've verified, I would appreciate it.

**Comment by dthree** [comment]
Thanks! :+1: 

Path `v1.3.27` published for you :)
