### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [dthree/vorpal#334]
Hi, what is the current status of this project?

**Comment by milesj** [comment]
@DanielRuf It's a bit dead atm. There's a few community members working on upgrades/forks, but not so much in the main repo.

**Comment by hongaar** [comment]
To date, I have not been able to find a real alternative. https://github.com/oclif/oclif looks pretty interesting but it lacks the interactive prompt.

Are there any active forks/branches? Would love to get involved, however not sure where to start...

**Comment by milesj** [comment]
@hongaar I mostly use oclif and yargs these days, but they are more just basic CLIs.

I believe @ore444 is working on a fork. https://github.com/dthree/vorpal/pull/328

**Comment by hongaar** [comment]
Quick update: there's an effort over at https://github.com/vorpaljs-reforged to _reforge_ vorpal by first porting it to TypeScript, update dependencies and maybe fix some bugs in the process.

There's also a Slack community for further discussion about this, [feel free to join!](https://join.slack.com/t/vorpal-workspace/shared_invite/enQtNTU3NTU3MTAzNzEyLTE4ODg2YjA1OTg0ZDMyY2I4M2Q3MGZhYjVlZDk1ZDY5NWJiZWFmYjJmYzk1ODdmYmU5ZjAzNGEzNDk5NDFhNWY)

**Comment by laurent22** [comment]
I use [terminal-kit](https://github.com/cronvel/terminal-kit) these days, which works very well and is actively maintained.

**Comment by hongaar** [comment]
_⚠ Shameless plug warning_

I've created a new project based on the Vorpal API in TypeScript which offers much of the same functionality: https://github.com/hongaar/bandersnatch.

Let me know if you have any feedback or features you are missing!

**Comment by DanielRuf** [comment]
> Let me know if you have any feedback or features you are missing!

Don't forget to invite additional contributors and move it to some org to increase the bus-factor and that more people can maintain it ;-)
