### ISSUE TITLE
Error stack trace is hidden when using promises

### ISSUE THREAD

**Issue by pgherveou** [dthree/vorpal#35]
The following just display a red Error: true instead of a full error logging
```js
import vorpal from 'vorpal'

const program = vorpal()

program.command('foo')
  .action(function() {
  return Promise.reject(new Error('Bouu'))
})

program
  .delimiter(`jogabo:work$`)
  .show()
```

**Comment by scotthovestadt** [comment]
It looks like the error object is just appended to the string: ````'Error: ' + err````. Probably need to look at the object and do more than typecast it.

**Comment by dthree** [comment]
Spot on, Scott. All good now. :+1:

**Comment by pgherveou** [comment]
Cool well done
