### ISSUE TITLE
command.after seems to do nothing

### ISSUE THREAD

**Issue by sugardave** [dthree/vorpal#362]
I'm working on expanding the [DefinitelyTyped Vorpal definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vorpal/index.d.ts) for my project where I want to use modes and I hate squiggly lines in my IDE.  And as part of that project, I've found that I want to remove a command from a mode that is already initialized but should now not be available conditionally based on another command in that mode.

From this:

```
mode ->
    commandA
    commandB
```
Running `commandB --some-option` should result in this:

```
mode ->
    commandB
```

Looking through the source I see there is `command.after` which I figured would be a fine place to do a find/remove shuffle.  But, it seems that nothing happens when the command finishes.  However, `command.done` is also available and that seems to fire and I am able to remove commandA.

I wonder if `command.after` is *supposed* to work or not to determine if I should bother adding it to the Vorpal types in DefinitelyTyped.

**Comment by solana-hiro** [comment]
You've correctly observed that command.after does not seem to execute as expected when the command finishes, while command.done does. 
Given this, it's reasonable to use command.done for your requirement.
Good luck.
