### ISSUE TITLE
Handle double quotation marks arguments as literal strings

### ISSUE THREAD

**Issue by fnky** [dthree/vorpal#38]
When passing arguments (or option values) surrounded with double quotes it should handle the input as literal strings and not split by any whitespace, nor should it parse it.

```js
vorpal
  .command('say <text>')
  .option('-n, --name <nm>')
  .action(function (args, cb) {
    this.log((args.options.name ? args.options.name + ': ' : '') + args.text)
    cb()
  })
```

```
node~$ say "Hello World"
Hello World
node~$ say 'Innovation distinguishes between a leader and a follower.' --name 'Steve Jobs'
Steve Jobs: Innovation distinguishes between a leader and a follower.
```

Currently only single quotation marks are supported. I would also propose quotation marks to be optional (both individually and collectively)

**Comment by dthree** [comment]
Good point. I'll get to this as soon as I can.

**Comment by dthree** [comment]
All good now.

Haha - that traced back to September commit where I was replacing double-quotes to singles and [accidentally replaced the regex](https://github.com/dthree/vorpal/commit/32dd6305ea2aa478cec085b6367638a80fe59b3b).

Whoops...
