### ISSUE TITLE
vorpal exits if backgrounded in shell

### ISSUE THREAD

**Issue by Downchuck** [dthree/vorpal#4]
The usual CTRL+Z does not seem to be working with vorpal in default config.
It does not like to be put in the background, restoring (via fg) exits.

**Comment by dthree** [comment]
I tried this and got it to restore - however the prompt seems to freeze.

https://github.com/nodejs/node-v0.x-archive/issues/3295

**Comment by dthree** [comment]
This looks like a `readline` issue.
