### ISSUE TITLE
CTRL+C twice won't exit process

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#44]
In my tests I have to hit CTRL+C three times. If I move the process.exit() call into the keypress handler instead of _sigint, it works correctly on the second keypress.

**Comment by dthree** [comment]
What terminal are you using?

**Comment by scotthovestadt** [comment]
iTerm on iOS. I'll look into debugging this issue and providing a pull request.

**Comment by dthree** [comment]
Thanks.

**Comment by dthree** [comment]
I did a fix - could you please try this again? I can't reproduce it.

**Comment by dthree** [comment]
Fixed `v1.5.2`.

https://github.com/dthree/vorpal/issues/55
