### ISSUE TITLE
CTRL+C clears the current command from the prompt and doesn't add it to history

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#46]
It should still be shown visibly on the command line UI, and you should be able to get at it via history. (This matches behavior of native command-line.)

**Comment by dthree** [comment]
Huh? Please clarify. I just tried on a standard ubuntu shell, and if I type:

`$ foo bar and the` and then press `CONTROL+C`, it doesn't save that to history.

If I am misduplicating, could you please clarify a little with an example? Thanks.

**Comment by scotthovestadt** [comment]
You're right, behavior isn't standard.
