### ISSUE TITLE
Inquirer.js' input types using odd-looking delimiter

### ISSUE THREAD

**Issue by timkurvers** [dthree/vorpal#48]
It seems that [Inquirer.js' input type](https://github.com/SBoudrias/Inquirer.js/#input----type-input-) renders rather strangely in Vorpal – lacking spacing and the green question mark:

<img width="236" alt="screen shot 2015-11-23 at 16 53 00" src="https://cloud.githubusercontent.com/assets/378235/11341531/17b5575a-9203-11e5-9964-290145e51ea6.png">

As opposed to the following in Inquirer.js:

<img width="237" alt="screen shot 2015-11-23 at 16 52 05" src="https://cloud.githubusercontent.com/assets/378235/11341609/6d8229d8-9203-11e5-9552-5e6f6a1e52d1.png">

Repro case:

```javascript
const prompt = function(object, callback) {
  object.prompt([
    {
      type: 'input',
      name: 'name',
      message: 'What is your name?',
      default: 'John Doe',
    },
    {
      type: 'list',
      name: 'list',
      message: 'What do cows drink?',
      choices: ['milk', 'water', 'applejuice'],
      default: 'water',
    }
  ], function(result) {
    callback();
  });
};
```

Using Vorpal:

```javascript
const cli = require('vorpal')();
cli
  .command('test')
  .action(function(args, callback) {
    prompt(this, callback);
  });

cli.show();
```

Using Inquirer.js:

```javascript
const inquirer = require('vorpal/node_modules/inquirer');
prompt(inquirer, function() {
  console.log(arguments);
});
```

Am unsure where this is going wrong, any ideas?

**Comment by dthree** [comment]
I use `inquirer`'s input as the default REPL prompt, so I make some modifications to it. I'll have to clean that up!

**Comment by timkurvers** [comment]
Thanks! Would you happen to know of any immediate work-arounds?

**Comment by dthree** [comment]
I would just make it yourself:
```
...
message: chalk.green('?') + ' What is your name? ',
...
```
This should work, I believe.

**Comment by dthree** [comment]
Vorpal extends Inquirer's prompt intentionally to omit the question mark and space. I've thought this over, and I'm not really going to change this. The workaround as above is really simple.
