### ISSUE TITLE
When installed as global NPM package, CTRL+C twice won't end process

### ISSUE THREAD

**Issue by scotthovestadt** [dthree/vorpal#55]
You can't kill it at all unless you manually ````pkill -9 node```` in another terminal.

**Comment by dthree** [comment]
Oh, interesting. Got it.

**Comment by scotthovestadt** [comment]
I've also discovered, at least in my project, although I'm returned to the command prompt when I kill the process via CTRL+C twice, the process isn't actually ending.

**Comment by eliperelman** [comment]
I've had this same issue as well, I added the following as a workaround:

```js
process.on('SIGINT', () => process.exit(2));
```

**Comment by dthree** [comment]
Thanks for the insight @eliperelman , I'll check this out as soon as I can.

**Comment by dthree** [comment]
Okay could you please try this out again with `v.1.5.1`. @eliperelman  @scotthovestadt

**Comment by scotthovestadt** [comment]
@dthree It doesn't work on my end. No change in behavior.

**Comment by dthree** [comment]
Rrrgh. I don't know why I still run Windows. Reproducing things sucks. 

--

Do you have an example Vorpal project I can download globally to try this out myself?

**Comment by scotthovestadt** [comment]
I'll take a crack at it now.

**Comment by dthree** [comment]
Thanks. If you just publish something real quick with the latest, I'll try it out. If I can reproduce this, I'm sure it's a real quick fix.

**Comment by scotthovestadt** [comment]
I don't know if I just didn't install it correctly before or if something in the 1.5.2 fixed it, but it works now. You can close this out!

**Comment by dthree** [comment]
Yeeha! That closes 3 issues haha!
