### ISSUE TITLE
Switching between instances will exit

### ISSUE THREAD

**Issue by jstrika** [dthree/vorpal#56]
In one of your [examples](https://github.com/dthree/vorpal/issues/9), you demonstrated how to switch between multiple instances. 
```javascript
function switch(vorpal) {
  vorpal.command('switch <instance>')
    .action(function (args, cb) {
      instances[args.instance].show();
    });
  return vorpal;
}

var instances = {
  'a': new Vorpal().use(switch).delimiter('a:'),
  'b': new Vorpal().use(switch).delimiter('b:'),
  'c': new Vorpal().use(switch).delimiter('c:'),
}
```
Using version 1.4.0, it does work on first ''switch'', but switching again to the same instance will exit. 

```javascript
$ node switcher.js
a: switch a
a: switch a
$
```

**Comment by dthree** [comment]
Erm, could you please try adding a callback to that method? i.e.

function switch(vorpal) {
  vorpal.command('switch <instance>')
    .action(function (args, cb) {
      instances[args.instance].show();
      cb();
    });
  return vorpal;
}

**Comment by jstrika** [comment]
Yep, that did the trick ;)

>For others to benefit': this feature allows us to create navigation between multiple menus. And if you push the instance name to an Array, you can add commands such a "back" or "show breadcrumbs" that can be shared between menus.

BTW: @dthree - great job with Vorpal !

**Comment by dthree** [comment]
Great and thanks!

:smile:
