### ISSUE TITLE
Required options do not throw error

### ISSUE THREAD

**Issue by eliperelman** [dthree/vorpal#60]
I'm using Vorpal with the reduced test case below:

```js
'use strict';

let cli = require('vorpal')();

cli
  .command('test')
  .description('reduced test case')
  .option('--required <val>', 'Should be a required value')
  .action(function(c) {
    console.log(c.options.required);
  });

cli.parse(process.argv);
```

```sh
node index test
```

This command's action should not execute using the given command, as no `--required` value was specified. According to the current source in lib/util.js:199, missing required options shows a message in the console along with help. This does not happen.

**Comment by toddpi314** [comment]
This is broken again on `1.12.0`

**Comment by rimiti** [comment]
Up for this issue. I have the same problem.
