### ISSUE TITLE
Input type 'password' shows characters while typing

### ISSUE THREAD

**Issue by berndb** [dthree/vorpal#67]
Until the return key is pressed, all password characters are shown as plain text:
```
password: my-secret-password
```

After the return key was pressed, the characters are replaced with `*` symbols:

```
password: ******************
```

As a sensitive user, I would like my password to be already hidden while typing. `*` symbols should be shown from the very beginning.

Is there an option to achieve this?

---

Example code:
```js
var vorpal = require('vorpal')();

vorpal
    .command('connect')
    .action(function (params, cb) {
        this.prompt([{
            type: 'password',
            name: 'password',
            message: 'password: '
        }], cb);
    });

vorpal.show();
vorpal.exec('connect');
```

**Comment by dthree** [comment]
Vorpal uses Inquirer.js inputs, so this would be a bug with Inquirer.js itself, I believe. Please file it there.

**Comment by berndb** [comment]
Inquirer does it just fine and shows `*`s during typing.

From what I can see in the code, you intercept inquirer's key press events and then you output the characters directly to the screen. This is probably why the `*`s don't show up.

---

Example with Inquirer@0.11.0:

```js
var inquirer = require('inquirer');

inquirer.prompt([{
    type: 'password',
    name: 'password',
    message: 'password: '
}], function () {
    console.log(arguments);
});
```

```
password: ******************
```

**Comment by dthree** [comment]
Oh got it.

**Comment by patrickdevivo** [comment]
+1 on a fix for this please. Any ideas?

**Comment by scotthovestadt** [comment]
Fixed. See: https://github.com/dthree/vorpal/pull/85

**Comment by dthree** [comment]
:+1:
