### ISSUE TITLE
.prompt() should return a Promise.

### ISSUE THREAD

**Issue by fiatjaf** [dthree/vorpal#74]
some methods of Vorpal (`.exec`, for example) return promises, while `.prompt` accepts a callback. Why not wrap this and return a promise instead?

**Comment by dthree** [comment]
Just have to do the work on this one.

**Comment by Shakyamuni177te** [comment]
I'll have a look into the issue see if there's anything I can do.

Also, I just had a job interview and it seems vorpal.js is well known enough for the people who were interviewing me to be aware of it already, and the people doing the interview seemed way ahead of the curve as far as new and emerging frameworks.

**Comment by dthree** [comment]
Hey, thanks. And that's awesome! :fire:

**Comment by fiatjaf** [comment]
@Shakyamuni177te are you still doing this?

**Comment by scotthovestadt** [comment]
Done.

**Comment by dthree** [comment]
:+1:
