### ISSUE TITLE
Autocomplete algorithm

### ISSUE THREAD

**Issue by fiatjaf** [dthree/vorpal#79]
The code that searches for matches for autocompletion at https://github.com/dthree/vorpal/blob/9a8cee1295415f5c3185add7acde6f047571b9f3/lib/session.js#L314-L364 works well for most cases, but it doesn't support, for example, typing the middle of the name of the command. It could perhaps be replaced by one of [these](http://fiatjaf.alhur.es/js-search-engines-comparison/) libraries somehow.

Would that be a change worth considering? Perhaps we should use extensions for this (and repack the current autocomplete function as an extension)? Perhaps just accepting an option for an autocomplete function during vorpal instantiation?

**Comment by ristomatti** [comment]
Not completely related but I used the autocomplete stuff just yesterday for creating tab completition to command arguments (values coming from a known list). I had some difficulties with it but eventually I got it working. I used the callback, commandInstance.match() function and a hacky reference to this.parent.ui.input(). I hope this would not break with the change :)

In case someone is interested the change is in this commit: https://github.com/ristomatti/lifxsh/commit/d342748e992807cd9fbc3c5b1310b73592624849

**Comment by dthree** [comment]
@fiatjaf got it. Would this suggested functionality mirror a bash CLI? My only requirement is that the autocompletion's functionality is an exact mirror of regular shell functionality. It's not clear when that proposal is. Could you give an exact example for me?

**Comment by dthree** [comment]
@ristomatti If we changed anything breaking, we would obviously apply semver and bump minor / major versions appropriately.

However, for that very reason you mentioned, I have been thinking of making an alternative, simplified manual autocompletion function, as I agree it currently kind of sucks. Perhaps we could discuss this?

**Comment by ristomatti** [comment]
@dthree great ideas! The syntax looks simple enough, especially for the simple list example. But if you consider a list of words:

    var words = ['red', 'green', 'blue];

and a command:

    vorpal.command('print <words...>', 'Print words');

Would the second example cover a use case where Vorpal would autocomplete the words so that only the ones not already listed would be used as dynamic values?

    > print red <tab>
    green  blue

Not sure if this would be a very common use case? I was just thinking yesterday how I could extend my current custom autocompletion to work like that...

@fiatjaf sorry for hijacking your issue!

**Comment by dthree** [comment]
It would do the default Unix-style handling, which in this case would not print anything if `red` was entered. But if `rojo` was another color and you entered `r`, it would print:

```
> print r
red rojo
```

**Comment by ristomatti** [comment]
I'll have think about that if I get it figured out. :) Not sure what you mean with the default Unix-style handling though. At least on my system (Linux Mint / bash) autocompletion for files works for multiple arguments also but I have to admit I don't remember if it has always been like that.

Anyhow, I don't want to sidetrack the conversation from the original issue more than this. The improvements you suggested would probably help others trying to figure out how the custom autocomplete is supposed to work. Keep up the good work!

**Comment by dthree** [comment]
Thanks! :+1: 

[BTW want a sneak peak at my next Vorpal pjt?](https://www.npmjs.com/package/cash) :smiley:

**Comment by ristomatti** [comment]
It looks a lot like an attempt to solve some problems I've always had when using Windows (I've used Cygwin a lot in the past). Really impressive stuff based on just the description and screenshots. I'll definately keep that in mind for those special Windows moments. Thanks for sharing! I'll probably be in contact at some point later on. Namely when I get proper documentation and NPM package done for the current project I'm working on currently (lifxsh), in case you maybe want to consider adding it to

**Comment by dthree** [comment]
Cool and thanks! Yeah, I'd love to see it.

**Comment by dthree** [comment]
@fiatjaf @ristomatti **ping**

I'm mid refactoring the autocompletion as gone over in this thread.

As this is a major refactor and the current design sucks, it's going to include breaking changes. Due to this, I'm going to deprecate `command.autocompletion()`, and introduce a new command, `command.tab()`.

I wanted to check with you guys (and anyone else who cares) on the name `.tab` - it's shorter, which is something I like, and makes sense to me as this is *tabbed autocompletion*. It also matches similar Vorpal semantics, such as `command.cancel` - it implies the action is being done.

This sound.... sound?

**Comment by scotthovestadt** [comment]
My vote is ````command.autocomplete````, stripping out the existing implementation and doing a major version bump.

I don't think ````command.tab```` tells me what it does if I'm just reading code. I might be a little confused.

Your call.

**Comment by dthree** [comment]
Thanks and I can see that. I just don't like the idea of hitting `2.0` over this little point. I can do `autocomplete`, but I do want to deprecate the other, and perhaps strip it when I have good enough reason to hit 2.0 (more changes).

**Comment by ristomatti** [comment]
I have to say I partly agree with @scotthovestadt on the naming. `command.tab` does not really tell anything it does. `command.autocomplete` would in my opinion be semantically similar to `command.cancel` as it's stating the action to be done instead of what the user does.

I don't see though why stripping the old implementation would be necessary. It can just be marked deprecated and remove it when the major version bump feels more just.

**Comment by fiatjaf** [comment]
I like `command.tab`. it is short and means _tabbed autocompletion_, instead of another kind of bizarre autocompletion that someone could think of.

But since this issue was originally about the builtin autocompletion for _command names_, not user-provided autocompletion, I must ask: are you doing something about it?

**Comment by ristomatti** [comment]
I can't quickly imagine what other autocompletion a user of a CLI module could expect to see, but how about `command.tabcomplete`? That'd be more descriptive while still being grammatically in the imperative mood.

**Comment by jeff-1amstudios** [comment]
I like @ristomatti's idea of `command.tabcomplete`. In terms of command autocompletion, I just submitted a PR to output the list of matching commands (if more than 1), tidy up the longestMatch algorithm and invoke custom autocompletion only when the current command is 'cmd[space]'.  Shouldn't impact the changes we're talking about here by the sounds of it. https://github.com/dthree/vorpal/pull/83

**Comment by jeff-1amstudios** [comment]
Also, my feeling is that autocompletion would be most awesome per-option. Eg I'd specify .option('--myOpt, 'description', ['val1', 'val2', 'val3'], and when the user enters `cmd --myOpt[space][tab] vorpal would autocomplete/print out the list of valid values.  Python prompt-toolkit does this _really_ nicely - see https://github.com/awslabs/aws-shell

**Comment by dthree** [comment]
Haha okay thanks for all your guys input! On the votes, we have:

`autocomplete` +2
`tab` +1
`tabcomplete` +2

Next vote will tip it over (and someone can change their mind).

---

@fiatjaf yes I am! I'm mid a *full* re-write on autocompletion, not just command autocompletion. However, I need a little more data from you. My last question to you:

> Would this suggested functionality mirror a bash CLI? My only requirement is that the autocompletion's functionality is an exact mirror of regular shell functionality. It's not clear when that proposal is. Could you give an exact example for me?

---

@jeff-1amstudios got it. See #83 for additional discussion on that.

**Comment by fiatjaf** [comment]
Ok, I'm sorry. I thought about the response to that, so I was kind of thinking that I had already sent it.

The answer is that it depends. What I wanted was actually not to mirror bash. I wanted autocompletion that looked inside the words of the commands, not one that only did prefix match. There's an example on the link I gave: http://fiatjaf.alhur.es/js-search-engines-comparison/ (start typing `vor`, for example, on the box at the top).

For these three libraries, I would like to use sifter, but since my comment was just an open suggestion and I realize not everyone would like my library, I think my real feature request here is: can somehow customize the autocompletion behavior? Vorpal could provide a smart default, but also a simple endpoint for customization, so I could, when needed, skip Vorpal's default autocompletion algorithm and use sifter.

**Comment by dthree** [comment]
Thanks. Yeah - I'm going to expose a totally raw method where you can do whatever you want.

---

Your link isn't pulling up anything for me... Just a Github ribbon. Tried it on Firefox and Chrome... could you possibly just give a quick example of what typing `vor` would do?

**Comment by fiatjaf** [comment]
Wait a little, it's heavy javascript! It will load. Or don't. Well, it is just a demo of three autocompletion/fuzzy-search libraries with the same stock of words, which results each library yields. It doesn't matter. Let's forget about this. I'm happy with your refactor, it will solve all problems everywhere.

**Comment by dthree** [comment]
Haha k. But your idea sounds cool, just trying to understand it.... I'm behind a proxy, so that might explain why the page isn't loading btw...

**Comment by dthree** [comment]
See https://github.com/dthree/vorpal/pull/83
