### ISSUE TITLE
Reading options beginning with a minus

### ISSUE THREAD

**Issue by AljoschaMeyer** [dthree/vorpal#8]
Would it be possible to support reading options starting with a minus?

In commander.js, `t -i -2` would assign -2 to `args.options.i`, whereas vorpal prints a friendly `Missing required option. Showing Help:`.
Tested on the same code as the other issue. `-i` or `--index` makes no difference.

```js
var Vorpal = require('./../../lib/vorpal');

var vorpal = new Vorpal();

vorpal.command('t')
.option("-i, --index <index>")
.action(function (args, cb) {
  console.log(args.options.index);
  cb()
});

vorpal.delimiter('foo:').show();
```

**Comment by dthree** [comment]
Good point. Yeah let me check this out.

**Comment by dthree** [comment]
Should be fixed.
