### ISSUE TITLE
optional arguments appearing in help menu

### ISSUE THREAD

**Issue by matthewoconnor-development** [dthree/vorpal#84]
Is there a way to have the help menu print without the ["your arg..."] appearing after the command? Fantastic cli tool but this little feature doesn't fit with our application. Any ideas would be great.

**Comment by dthree** [comment]
Hey, thanks!

I happened to have it planned this week to introduce a `vorpal.help` method that will override the automated help. Would this work?

**Comment by matthewoconnor-development** [comment]
Yes that would probably work nicely, its non critical so I can push it out as an update. thanks

**Comment by dthree** [comment]
Sure, no problem.

**Comment by dthree** [comment]
Okay there's a new command, `vorpal.help(fn)`, which lets you do a totally custom help menu.

To access the list of commands registered to vorpal, it's `this.commands`. You can play around with it from there.

**Comment by dthree** [comment]
Wiki: https://github.com/dthree/vorpal/wiki/API-|-vorpal#vorpalhelpfunction

Feel free to add clarity to them if you want.
