### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by dthree** [dthree/vorpal#87]
Anyone good at making Single Page sites? I'm working on a concept for `vorpal.js.org`, but I don't have too much experience on responsive front-end sites, so it'll probably take me a bit. 

If you're interested in helping, let me know and I'll shoot you what I've got cooking so far!

**Comment by Shakyamuni177te** [comment]
I've done some before and I certainly wouldn't have a problem doing it. However, I know another web designer who is much, much better than me and just getting started freelance. I'll see if she's interested and cover the expenses out of my own pocket if you like :).

**Comment by Shakyamuni177te** [comment]
Wing me an e-mail to peter.carter.mail@gmail.com with the specs and anything else you need, along with a provisional deadline if you think one is appropriate and I'll make sure it gets done.

**Comment by dthree** [comment]
Thanks @Shakyamuni177te , as gone over in email.

---

I got the domain registered based on Vorpal `gh-pages` branch, and put up a very basic starting template for site. Suggestions / contributions appreciated!

http://vorpal.js.org/

**Comment by Shakyamuni177te** [comment]
The site looks very good as is but I will have a look at the code this weekend when I'm off work and hopefully there is something I can improve further -- I have a feeling there are some subtle improvements we can make to the stylings :). Also, I will see if there is a way Vorpal.js will help with the website we're putting together at work.

**Comment by dthree** [comment]
Okay great! Yeah there's room for a ton of improvements!

**Comment by dthree** [comment]
Okay, I've got the basics for the site done, and just submitted to HN, wish me luck! :smile:

**Comment by Shakyamuni177te** [comment]
Spoke to the web designer and she says she'll take a look at the project over the weekend to see if there's anything she can do to fix it up. We agree there is a potential "White Space" issue but are unsure how to proceed at present. Will seek additional consultation. Just looking into issues with promises myself at the moment, spurred partly by the promises within your own code;

**Comment by dthree** [comment]
Thanks! Appreciate it!
