### ISSUE TITLE
Multiple choice type?

### ISSUE THREAD

**Issue by kevinSuttle** [dthree/vorpal#91]
Example from Yeoman. 

<img width="745" alt="screen shot 2016-02-03 at 11 34 54 pm" src="https://cloud.githubusercontent.com/assets/95672/12805925/d793d872-cace-11e5-8c11-02e119623015.png">

Is this possible with Vorpal?

**Comment by dthree** [comment]
Yes it is! Vorpal uses [Inquirer.js](https://github.com/sboudrias/Inquirer.js) for prompts, which was built for Yeoman originally. @sboudrias

**Comment by kevinSuttle** [comment]
:+1: Thanks!

**Comment by dthree** [comment]
No problem. :smiley:
