### ISSUE TITLE
Outputs delimeter+command after giving a command in GitBash (Windows 7)

### ISSUE THREAD

**Issue by MatteoGgl** [dthree/vorpal#92]
I was just trying the tutorial linked in the front page and when testing it, my CLI interface has an error in displaying the output:

``` bash
$ node daffy.js
daffy$ duck <--- Input 
daffy$ duck <--- Repeated by the CLI
Wabbit
daffy$
```

Outputs works correctly on Windows cmd.

**Comment by dthree** [comment]
What OS / terminal?

**Comment by MatteoGgl** [comment]
Terminal is GitBash (MINGW64), installed with Git for Windows. OS is
Windows 7.

On Fri, Feb 5, 2016 at 5:14 PM, dc <notifications@github.com> wrote:

> What OS / terminal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dthree/vorpal/issues/92#issuecomment-180424694>.
>



-- 

Matteo Guglielmetti

*Web developer*




*Click Shop | Komlab*Passaggio della Torre dell’Acqua, 2

35016 Piazzola sul Brenta (PD)

T. 049 635884

**Comment by dthree** [comment]
Okay thanks I'll check it out.
