### ISSUE TITLE
y/N command issue?

### ISSUE THREAD

**Issue by matt-oc** [dthree/vorpal#98]
I have noticed when typing exit or quit to bring up the y/N prompt if i type "y" it quits as expected but if I type N in shows the delimiter but doesn't seem to enter the repl again, commands cant be entered and need to ^C to get out of it. This may be something I have done wrong, just wondering if you have come across it before. thanks

**Comment by dthree** [comment]
I think this is an issue on Windows. I'll check it out further. But in the meantime, I'm thinking of getting rid of the `y/N` on quit. What do you think?

**Comment by matthewoconnor-development** [comment]
It is on mac I am having the issues, I think if it just exited it would be better alright, no need for the y/n prompt. I do like the fact quit works as exit too, I would keep that for sure.

**Comment by matt-oc** [comment]
@dthree Any update on this issue? I'm happy to fork and remove the y/N myself but wont bother if you have a fix coming.

**Comment by dthree** [comment]
Not mid anything, trying to get to it soon. Feel free to jump in - it's an easy PR. :sunglasses:

**Comment by matt-oc** [comment]
@dthree I quickly removed the y/n business and it works great, any thoughts on perhaps an alternative more generic text for the "Exits instance of vorpal" in the help menu? It doesnt make alot of sense (in my application at least) to have it say that.

**Comment by dthree** [comment]
Sure - could you please change it to say `Exits application`? It should be in `./lib/vorpal-commons.js`. Ensure you do separate commits for these two changes.

:+1:

**Comment by dthree** [comment]
You fixed this!
